### ISSUE TITLE
HFValidationError when load snac_24khz

### ISSUE THREAD

**Issue by VJJJJJJ1** [hubertsiuzdak/snac#21]
hi there, when I download snac_24khz and load it locally, some error happened:
```
Traceback (most recent call last):
  File "/tsdata2/wwj/mini-omni/test.py", line 2, in <module>
    snacmodel = SNAC.from_pretrained("/tsdata2/wwj/mini-omni/model/snac_24khz").eval().to(device)
  File "/work/anaconda3/envs/omni/lib/python3.10/site-packages/snac/snac.py", line 103, in from_pretrained
    config_path = hf_hub_download(repo_id=repo_id, filename="config.json", **kwargs)
  File "/work/anaconda3/envs/omni/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/work/anaconda3/envs/omni/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/work/anaconda3/envs/omni/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/tsdata2/wwj/mini-omni/model/snac_24khz'. Use `repo_type` argument if needed.
```
I use SNAC.from_pretrained and the code as follows:
```
from snac import SNAC
snacmodel = SNAC.from_pretrained("/tsdata2/wwj/mini-omni/model/snac_24khz").eval().to(device)
```
thank you for your reply！

**Comment by isruihu** [comment]
I meet the same problem
